### ISSUE TITLE
Bot State API is deprecated

### ISSUE THREAD

**Issue by chrisvella** [alyssaong1/botframework-smalltalk#2]
My local version fails with this error:

```
Server listening on port 3979
ChatConnector: message received.
ChatConnector: message received.
ChatConnector: message received.
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
UniversalBot("*") routing "hi" from "emulator"
Session.beginDialog(/)
/ - waterfall() step 1 of 1
/ - Session.sendBatch() sending 0 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
/ - Session.send()
/ - Session.sendBatch() sending 1 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.
```

**Comment by alyssaong1** [comment]
@chrisvella Thanks for notifying. FYI the bot should still respond to your messages. In the recent version of botbuilder, the Bot State API has been deprecated hence the warning message. In any case, I've made a fix: https://github.com/alyssaong1/botframework-smalltalk/commit/3dedf3278d007754a7a07910dbcc158229249774

Note that this is an in-memory solution - best not used in production but OK for testing locally. See the instructions at https://aka.ms/I6swrh for how to replace it with proper storage like Cosmos DB.
