### ISSUE TITLE
Leading question mark in smalltalk.dialog.sorry KB answer

### ISSUE THREAD

**Issue by daneeq** [alyssaong1/botframework-smalltalk#5]
Hi, 

I'm playing with implementing smalltalk in Bot Framework and this has been super helpful. So thank you. :) I've just translated it to Czech for local purposes. However, one thing got me confused:

In the knowledge base, you have a leading question mark in all the answers for the sorry intent,
 so it says `?smalltalk.dialog.sorry`
(https://github.com/alyssaong1/botframework-smalltalk/blob/master/smalltalkkb.tsv#L943)

Was there a specific reason for this? It causes a mismatch, so it doesn't provide the correct answer if the user happens to trigger this. 

Thanks

**Comment by alyssaong1** [comment]
Thanks for pointing this out - this is definitely a bug not a feature :) 

Fixed https://github.com/alyssaong1/botframework-smalltalk/commit/d5e7e80aa064193711cf3a97b297eb255ce28ded
