### ISSUE TITLE
Why QnAMakerRecogniser creates intent on Luis?

### ISSUE THREAD

**Issue by mohd-ismail-siddiqui** [alyssaong1/botframework-smalltalk#9]
@luhan2017 As I can see in one of my bot project where I have used both LUIS and QnAMaker. When I built the project and run it. I have seen in Luis app, there is an intent like **DeferToRecognizer_QnA_VirtualTravelAssistant**.

But When I created another project, where I have added one more intent (except Greeting and Unknown) i.e. QnA Intent Recognized, then I observed that there is no LUIS created and no intent found.

Please help me to understand this.

**Comment by mohd-ismail-siddiqui** [comment]
This is not related to this repository.

**Comment by luhan2017** [comment]
Greeting and Unknown are not luis intents. they are just common triggers. 

The DeferToRecognizer is a crosstrain intent, which would be only generated if both luis and qna is configured.
